/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
      extend: {
        colors: {
          "secondary": "#48626e",
          "on-secondary-container": "#4e6874",
          "on-tertiary-fixed": "#271900",
          "on-surface": "#191c1e",
          "primary-container": "#1b2b48",
          "on-secondary": "#ffffff",
          "on-secondary-fixed": "#021f29",
          "outline-variant": "#c5c6ce",
          "surface-tint": "#4f5e7e",
          "surface-dim": "#d8dadc",
          "inverse-surface": "#2d3133",
          "error": "#ba1a1a",
          "on-primary": "#ffffff",
          "on-primary-fixed": "#091b37",
          "surface-bright": "#f8f9fb",
          "tertiary-container": "#3b2800",
          "tertiary-fixed-dim": "#e3c28a",
          "tertiary-fixed": "#ffdea7",
          "surface-variant": "#e0e3e5",
          "surface-container-low": "#f2f4f6",
          "on-tertiary-container": "#ac8e5b",
          "on-tertiary": "#ffffff",
          "secondary-fixed": "#cbe7f5",
          "surface-container": "#eceef0",
          "surface": "#f8f9fb",
          "surface-container-lowest": "#ffffff",
          "primary-fixed-dim": "#b7c7eb",
          "background": "#f8f9fb",
          "primary": "#041632",
          "surface-container-highest": "#e0e3e5",
          "tertiary": "#211500",
          "on-primary-fixed-variant": "#374765",
          "secondary-fixed-dim": "#afcbd8",
          "error-container": "#ffdad6",
          "on-error-container": "#93000a",
          "inverse-primary": "#b7c7eb",
          "primary-fixed": "#d7e2ff",
          "on-error": "#ffffff",
          "outline": "#75777e",
          "on-tertiary-fixed-variant": "#594317",
          "on-primary-container": "#8393b5",
          "secondary-container": "#cbe7f5",
          "inverse-on-surface": "#eff1f3",
          "on-surface-variant": "#44474d",
          "on-background": "#191c1e",
          "surface-container-high": "#e6e8ea",
          "on-secondary-fixed-variant": "#304a55"
        },
        fontFamily: {
          "headline": ["Manrope", "sans-serif"],
          "body": ["Inter", "sans-serif"],
          "label": ["Inter", "sans-serif"],
          "manrope": ["Manrope", "sans-serif"],
          "inter": ["Inter", "sans-serif"]
        },
        borderRadius: {
          "DEFAULT": "0.125rem", 
          "lg": "0.25rem", 
          "xl": "0.5rem", 
          "full": "0.75rem"
        },
        animation: {
          fadeIn: 'fadeIn 0.2s ease-in-out',
        },
        keyframes: {
          fadeIn: {
            '0%': { opacity: '0', transform: 'translateY(-4px)' },
            '100%': { opacity: '1', transform: 'translateY(0)' },
          },
        },
      },
    },
    plugins: [],
  }